import blog1 from '../assets/images/blog1.jpg';
import blog2 from '../assets/images/blog2.jpg';
import blog3 from '../assets/images/blog3.jpg';


const BlogData = [
    {   
        id: 1,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus tempore velit quam blanditiis. Ut vero, accusamus quos aperiam deserunt exercitationem eligendi soluta recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere,  `,
        image: blog1,
    },
    {
        id: 2,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus tempore velit quam blanditiis. Ut vero, accusamus quos aperiam deserunt exercitationem eligendi soluta recusandae natus,  Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog2,
    },
    {
        id: 3,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 4,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 5,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 6,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 7,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 8,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 9,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    {
        id: 10,
        title: ' Lorem ipsum dolor sit amet.',
        desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. A corrupti officia fugiat eveniet ut ipsum magni necessitatibus dicta et minima! Tempora repellat commodi assumenda sint! Itaque repudiandae doloribus obcaecati eos, eius, ex incidunt voluptates sapiente, officia aut culpa nobis laudantium vero. Recusandae, velit ipsum ab nihil, nobis sint fuga atque eaque aperiam esse reprehenderit saepe animi eum facilis. Praesentium fugit autem aspernatur est, ullam, minima neque dolorem numquam quia aut, perspiciatis a accusantium iusto dolor esse laudantium sit temporibus incidunt! Incidunt porro saepe quisquam! Possimus illum ex repellendus numquam enim tempora ducimus sapiente, nulla optio similique corporis, incidunt molestiae eveniet, ullam ratione voluptatum itaque iste ut dolore nisi? Cupiditate labore, in quae maxime aperiam non illo fugit quis porro veritatis enim rem perspiciatis praesentium facere earum omnis quod? Corrupti illum possimus recusandae natus, tenetur aut magnam mollitia ex earum. Dignissimos, voluptatum? Eum in impedit accusantium fuga velit. Unde officia ut eius, quos laborum fugiat odio praesentium qui quidem aut dolor soluta, eligendi odit magnam aperiam natus dicta quia, voluptates suscipit! Corporis laudantium labore facere, laboriosam similique quibusdam, animi quas temporibus enim voluptatibus et ratione sit iste ipsum!`,
        image: blog3,
    },
    
  ]
export { BlogData };

