
const ActionType = {
    getProductList: 'GET-PRODUCT-LIST',
    getLoadProducts: 'ALL-PRODUCTS',
    getProductDetail: 'GET-PRODUCT-DETAIL',
    deleteProduct:'DELETE-PRODUCT',
    ADD_NEW_PRODUCT:'ADD-NEW-PRODUCT',
    UPDATE_PRODUCT:'UPDATE-PRODUCT',

    setToken: 'SET-TOKEN',
    unSetToken: 'UN-SET-TOKEN',
    LOGOUT: 'USER-LOGOUT',
    registration: 'REGISTRATION',
    login:'LOGIN',
    MY_INFO:'MY-INFO',
    USER_INFO:'USER-INFO',
    UPDATE_MY_INFO:'UPDATE-MY-INFO',
    USER_LIST:'USER-LIST',
    
    ADD_TO_CART: 'ADD-TO-CART',
    GET_CART_ITEMS: 'GET-CART-ITEMS',
    REMOVE_FROM_CART: 'REMOVE-FROM-CART',
    UPDATE_CART: 'UPDATE-CART',
    CHECKOUT: 'CHECKOUT',
    MY_ORDERS:'MY-ORDERS',
    GET_ALL_ORDERS:'GET-ALL-ORDERS',
    GET_ALL_ORDER_ADMIN:'GET-ALL-ORDERS-ADMIN',
    UPDATE_ORDER:'UPDATE-ORDER',
    GET_ORDER_DETAIL:"GET-ORDER-DETAIL",
    ADD_NEW_CATEGORY: 'ADD-NEW-CATEGORY',
    GET_CATEGORY_LIST: 'GET-CATEGORY-LIST',
    DEL_CATEGORY: 'DEL-CATEGORY',
}
export default ActionType;